version: 5
daemon:
  log_level: info
  admin_group: wheel
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:7590-1DA2:E493-0000:03:00.0:
    fan_control_enabled: false
    pmfw_options:
      zero_rpm: true
    power_cap: 200.0
    performance_level: auto
    voltage_offset: -35
current_profile: null
auto_switch_profiles: false

